import type { Crowd, Game, MapObject } from "./types";

const objects: MapObject[] = [
  {
    id: "door",
    label: "南門",
    kind: "door",
    x: 50,
    y: 93,
    w: 14,
    h: 8,
    z: 4,
    desc: "朝南的雙開木門，通往雨濕的街道",
  },
  {
    id: "bar",
    label: "長吧台",
    kind: "furniture",
    x: 50,
    y: 16,
    w: 72,
    h: 14,
    z: 1,
    desc: "沿北牆的深色長吧台，瓶架與銅龍頭",
  },
  {
    id: "stools",
    label: "吧凳",
    kind: "furniture",
    x: 48,
    y: 27,
    w: 50,
    h: 8,
    z: 3,
    desc: "一排面向吧台的圓凳",
  },
  {
    id: "fireplace",
    label: "石壁爐",
    kind: "landmark",
    x: 12,
    y: 48,
    w: 16,
    h: 22,
    z: 1,
    desc: "西牆巨大石砌壁爐，火光還在",
  },
  {
    id: "rug",
    label: "爐前毯",
    kind: "furniture",
    x: 24,
    y: 50,
    w: 14,
    h: 16,
    z: 2,
    desc: "壁爐前磨舊的織毯",
  },
  {
    id: "table-fire",
    label: "爐邊圓桌",
    kind: "furniture",
    x: 38,
    y: 44,
    w: 14,
    h: 14,
    z: 3,
    desc: "靠近壁爐的圓桌與椅",
  },
  {
    id: "table-mid",
    label: "中央圓桌",
    kind: "furniture",
    x: 52,
    y: 52,
    w: 14,
    h: 14,
    z: 3,
    desc: "廳中央的圓桌",
  },
  {
    id: "table-east",
    label: "東側圓桌",
    kind: "furniture",
    x: 64,
    y: 46,
    w: 13,
    h: 13,
    z: 3,
    desc: "偏東的圓桌",
  },
  {
    id: "table-south",
    label: "近門圓桌",
    kind: "furniture",
    x: 46,
    y: 68,
    w: 13,
    h: 13,
    z: 3,
    desc: "靠近南門的圓桌",
  },
  {
    id: "stairs",
    label: "上樓梯",
    kind: "door",
    x: 84,
    y: 80,
    w: 16,
    h: 18,
    z: 2,
    desc: "東南角木梯，通往客房",
  },
  {
    id: "barrels",
    label: "酒桶堆",
    kind: "container",
    x: 84,
    y: 20,
    w: 16,
    h: 16,
    z: 2,
    desc: "東北角酒桶與木箱",
  },
  {
    id: "kitchen",
    label: "廚房傳菜口",
    kind: "landmark",
    x: 18,
    y: 12,
    w: 14,
    h: 10,
    z: 3,
    desc: "西北角通往廚房的傳菜口",
  },
];

const crowds: Crowd[] = [
  {
    id: "crowd_bar",
    label: "吧台前的酒客",
    x: 48,
    y: 28,
    rx: 18,
    ry: 8,
    size: 5,
    desc: "兩三個水手把聲音壓在銅杯裡，沒人抬頭",
    namedOut: 0,
  },
];

export function sampleGame(): Game {
  const now = Date.now();
  const sceneId = "scene_tavern";
  return {
    version: 1,
    id: `game_sample_${now}`,
    title: "雨夜〈北風亭〉",
    theme: "港口雨夜，一家不肯打烊的旅店",
    imageStyle: "水墨與舊紙色的手繪風，低飽和、沉鬱、細膩筆觸",
    mapStyle: "水墨與舊紙色的手繪風，低飽和、沉鬱、細膩筆觸",
    portraitStyle: "水墨與舊紙色的手繪風，低飽和、沉鬱、細膩筆觸",
    createdAt: now,
    updatedAt: now,
    turnCount: 0,
    lorebook: [
      {
        id: "lb1",
        title: "北風亭",
        content:
          "開在舊碼頭第三街的木造旅店。招牌被風吹歪，可爐火從不熄。水手、更夫、躲債的人都來這裡把聲音壓低。",
        tags: ["場所", "北風亭"],
        constant: true,
      },
      {
        id: "lb2",
        title: "今晚的雨",
        content:
          "雨從黃昏下到現在。街上的油燈只剩兩盞，碼頭吊車停著。有人說潮水比月曆提早了一尺。",
        tags: ["天氣", "潮水"],
        constant: true,
      },
      {
        id: "lb3",
        title: "阿秋",
        content:
          "吧台後的老闆娘。左手缺半截小指，調酒時用銅量杯敲桌沿計時。不喜歡有人問她以前在船上做什麼。",
        tags: ["人物", "阿秋"],
        constant: false,
      },
      {
        id: "lb4",
        title: "禁問的房間",
        content:
          "樓上 3 號房從上週起一直亮著燈，可鑰匙在阿秋圍裙裡。沒人被允許送熱水上去。",
        tags: ["謎", "阿秋", "3號房"],
        constant: false,
      },
      {
        id: "lb5",
        title: "潮汐哨",
        content:
          "更夫用的銅哨，吹兩短一長代表「潮來了」。今晚還沒有人吹過。",
        tags: ["物件", "阿青", "更夫", "潮汐哨"],
        constant: false,
      },
    ],
    player: {
      id: "player",
      name: "林拾",
      role: "player",
      bio: "剛下船的記帳助手，懷裡有一封不該拆的信，要在黎明前交給「聽得見潮聲的人」。",
      age: 24,
      gender: "男",
      race: "人",
      appearance:
        "短黑髮被雨貼在額上，眉濃，眼細長帶血絲，鼻梁正，嘴唇薄而乾裂。膚色偏暗，下頜有一層鹽霜。肩寬腰窄，指節粗，右手虎口有墨漬。",
      clothing:
        "深色短襖袖口鹽白，裡襯還潮；灰布綁腿，舊皮靴底夾著沙。腰間掛一只空菸袋，懷裡油紙信的邊從襟口露出一角。沒戴帽，肩上還在滴水。",
      color: "#f4f1ea",
      x: 50,
      y: 82,
      status: "剛推門進來，雨水還在下巴。",
    },
    inventory: ["未拆的油紙信", "半包受潮的菸"],
    flags: { letter: "未拆" },
    scenes: {
      [sceneId]: {
        id: sceneId,
        name: "北風亭·一樓",
        summary:
          "木造旅店一樓。北牆長吧台，西牆壁爐，東南角樓梯，南門通往雨街。廳裡有幾張圓桌，人不多，可空氣很滿。",
        atmosphere: "濕羊毛、炭火、廉價酒。雨打在門板上像有人用指節敲門。",
        mapImage: "/maps/tavern.jpg",
        mapSource: "sample",
        mapAspect: "1:1",
        walkableNotes:
          "中央地板與桌間走道可走。吧台表面、壁爐石座、酒桶堆、桌面不可穿。南門可出街，東南梯可上樓。",
        objects,
        crowds,
        playerPos: { x: 50, y: 82 },
        npcs: [
          {
            id: "npc_qiu",
            name: "阿秋",
            trueName: "阿秋",
            known: false,
            alias: "深褐圍裙的女人",
            role: "npc",
            bio: "北風亭老闆娘，缺半截小指，聲音不高。",
            personality: "話少、不耐閒聊，問到船上的事會把話題掐死。",
            age: 36,
            gender: "女",
            race: "人",
            tags: ["阿秋", "北風亭", "老闆娘"],
            appearance:
              "髮用銅簪挽成髻，幾綹碎髮貼在頰邊。眉淡，眼圓而疲，鼻小，唇色暗。膚色暖褐，頸細。右手小指缺半截，指腹有酒漬。身材中等偏軟，胸形圓、分量中等，圍裙下能看出起伏；腹微隆，不是產後的鬆垮，是長站的實。臀寬過肩，圓而沉，重心常放左腳。",
            clothing:
              "深褐圍裙罩在舊醬色短衫外，圍裙口袋沉著鑰匙。深色長褲挽到踝上，布鞋後跟磨平。腕上細銅鐲，耳垂一粒暗珠。沒戴帽。",
            color: "#a67c6d",
            x: 52,
            y: 14,
            facing: 180,
            alert: "unaware",
            status: "在吧台後擦一只量杯，沒抬頭。",
            goal: "今晚別讓人問起樓上那盞燈",
            memory: "3號房亮著，鑰匙在圍裙裡。",
          },
          {
            id: "npc_hou",
            name: "老侯",
            trueName: "老侯",
            known: false,
            alias: "霧鏡圍巾的老人",
            role: "npc",
            bio: "退休的碼頭書記，每晚佔壁爐旁那桌，聽雨勝過人話。",
            personality: "慢熱、愛聽不愛答，開口常像在對雨說話。",
            age: 71,
            gender: "男",
            race: "人",
            tags: ["老侯", "碼頭"],
            appearance:
              "稀疏白髮貼著頭皮，眉長而亂，眼窩深，鏡片後眼睛細。鼻頭紅，唇薄，下頜青碴。膚色灰黃，肩微駝，手指細長、關節腫。",
            clothing:
              "灰色羊毛圍巾繞到下頜，舊青長衫，袖口磨白。深色布褲，棉鞋沾爐灰。眼鏡起霧，沒戴帽，腰間沒有袋。",
            color: "#7d9aa3",
            x: 36,
            y: 44,
            facing: 90,
            alert: "unaware",
            status: "坐在爐邊圓桌，杯沿對準壁爐。",
            goal: "聽雨，別被生人打斷",
            memory: "每晚這張桌。潮水比月曆早。",
          },
          {
            id: "npc_qing",
            name: "阿青",
            trueName: "阿青",
            known: false,
            alias: "青披風的人",
            role: "npc",
            bio: "巡夜的更夫，銅哨在腰帶上。今晚她在門邊躲雨，還不是進來歇腳的時間。",
            personality: "警覺、話硬，不熟的人只肯用最短的句子。",
            age: 27,
            gender: "女",
            race: "人",
            tags: ["阿青", "更夫", "潮汐哨"],
            appearance:
              "髮剪到耳下，被雨打成一綹綹。眉平，眼亮而銳，鼻直，唇緊。膚色冷白，顴骨高。肩背挺，手背有凍傷痕跡，小腿結實。胸形扁圓、量感不大，呼吸時鎖骨下才見起伏；腹平坦、腰線直，長期走路練出來的。臀緊而窄，不圓，與肩差不多寬。",
            clothing:
              "深青披風連帽沒戴上，裡層短褐，綁腿，靴底帶泥。腰帶穿一只銅哨、一圈麻繩。沒有飾品。",
            color: "#8a8e7a",
            x: 62,
            y: 86,
            facing: 200,
            alert: "unaware",
            status: "靠在近門的柱邊，聽外面的雨勢。",
            goal: "躲完這陣雨再去吹哨",
            memory: "潮汐哨還沒吹。門邊不是歇腳的時候。",
          },
        ],
      },
    },
    currentSceneId: sceneId,
    log: [
      {
        id: "log_open",
        at: now,
        kind: "narrative",
        text: "門軸叫了一聲。雨被留在門外，熱氣立刻貼上臉。北風亭的一樓比你記憶中更暗——壁爐在西牆，吧台在最北，樓梯在東南角陰著。吧台後有人在擦杯子，沒有問你要什麼。爐邊坐著一個戴眼鏡的老人。門邊還站著一個披青衣的人，銅哨偶爾碰到皮帶扣，輕響。\n\n你站在門口的濕地板上。再走幾步才進得了廳中央；若要跟人說話，得先走近。",
      },
    ],
    suggested: [
      "走到吧台向挽圍裙的女人要一杯熱的",
      "在爐邊坐下，聽那個戴霧鏡的老人有沒有在說話",
      "問門邊披青衣的人雨還要下多久",
      "推門走回街上",
    ],
  };
}
